#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0

# Che-Theia workflow

cache: false
git:
  depth: false 

language: node_js
node_js: "12.20.1"

before_install:
  - nproc
  - cat /sys/fs/cgroup/cpuset/cpuset.cpus
  - free -h
  # use buildkit
  - export DOCKER_BUILDKIT=1
  - export BUILDKIT_PROGRESS=plain

install:
  # TODO when we're confident that sha-tagged travis-built images won't collide with GHA built ones, we can remove the -travis suffix here
  - export SHORT_SHA=$(git rev-parse --short HEAD)-travis
  #- export GITHUB_TOKEN="$CHE_BOT_GITHUB_TOKEN"
  #- echo "$RH_CHE_AUTOMATION_DOCKERHUB_PASSWORD" | docker login -u "$RH_CHE_AUTOMATION_DOCKERHUB_USERNAME" --password-stdin
  #- echo "$QUAY_ECLIPSE_CHE_PASSWORD" | docker login quay.io -u "$QUAY_ECLIPSE_CHE_USERNAME" --password-stdin

env: 
  global:
  - TAG=next-travis
  - REGISTRY=quay.io
  - ORGANIZATION=eclipse
  - PR_NUMBER=

jobs:
  include: 
    - &node-build
      stage: Build node
      name: Node Build on power-hdc
      os: linux-ppc64le
      install:
        - sudo apt-get update && sudo apt-get install -y libsecret-1-dev
      script: yarn
      env: INFRA=HDC
    - <<: *node-build
      name: Node Build on power-pok
      os: linux-ppc64le
      group: lxd
      env: INFRA=POK-BAREMETAL
    - <<: *node-build
      name: Node Build on power-pok-nvme-vm
      os: linux-ppc64le
      group: genesis
      env: INFRA=POK-NVME-VM
    - <<: *node-build
      name: Node Build on ibmcloud
      os: linux-ppc64le
      group: ibm-cloud
      env: INFRA=IBMCloud
    
    - &docker-build
      name: Docker build (ubi8) on HDC-POK
      os: linux-ppc64le
      stage: docker build
      env: DIST=ubi8 INFRA=HDC
      install: skip
      script:
      - |
        set -e
        docker image prune -a -f
        docker pull quay.io/eclipse/che-theia-dev:next-travis && \
        docker tag quay.io/eclipse/che-theia-dev:next-travis eclipse/che-theia-dev:next-travis || true
        TAG=$TAG-$(arch) ./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.$DIST
    - <<: *docker-build
      name: Docker build (ubi8) on power-pok
      os: linux-ppc64le
      group: lxd
      env: DIST=ubi8 INFRA=POK-BAREMETAL
    - <<: *docker-build
      name: Docker build (ubi8) on power-pok-nvme-vm
      os: linux-ppc64le
      group: genesis
      env: DIST=ubi8 INFRA=POK-NVME-VM
    - <<: *docker-build
      name: Docker build (ubi8) on ibmcloud
      os: linux-ppc64le
      group: ibm-cloud
      env: DIST=ubi8 INFRA=IBM-Cloud

   
